spring.application.name=gateway-service-api

server.port=9090

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}


keycloak.realm=hotel-management-realm
keycloak.auth-issure-uri=http://localhost:8080/realms/hotel-management-realm
keycloak.client=travel-ease-client

logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.com.example.demo.filter=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


management.endpoints.web.exposure.include=health,info,metrics,gateway,routes
management.endpoint.health.show-details=always
management.endpoint.gateway.enabled=true

